### PR TITLE
Fix typos in project docs

### PR DESCRIPTION
**Pull request by ShaneCurcuru**

### CODE REVIEW

**Review by ShaneCurcuru — COMMENTED** [review]
Can I add the DCO here? Or does it need to be in a completely separate commit?  (Note: I use GitHub UI/Desktop, not git)

Signed-off-by: Shane Curcuru <shane@punderthings.com>

**Comment by ShaneCurcuru** [comment]
Is there any way to get the DCO check to re-run, so this is mergeable?  Or should we just close this and I can start with a fresh copy of everything, and then remember to add the signoff?

Also, if this project - which wants to attract non-coders (i.e. people who will be using GitHub, not git, to contribute), then you should consider setting the GitHub repo to enforce signoffs:

https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/#how-to-enable-required-signoffs-for-a-repository

**Comment by caniszczyk** [comment]
@ShaneCurcuru problem is first commit doesn't have the DCO so that's why it's still failing

We do enable this setting on all TODO repos btw :)

I think easiest option is to close this and resubmit the PR (cc: @anajsana to help out)

**Comment by ShaneCurcuru** [comment]
Replaced by PR #18

**Pull request closed without merging**
